version: '3.4'

services:
  expertstore.ordering:
    image: ${DOCKER_REGISTRY-}expertstoreordering
    build:
      context: .
      dockerfile: src/ExpertStore.Ordering/Dockerfile
    ports:
      - 50080:80

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672

  paymentsprocessor:
    image: ${DOCKER_REGISTRY-}paymentsprocessor
    build:
      context: .
      dockerfile: src/PaymentsProcessor/Dockerfile

  external.thecarrier:
    image: ${DOCKER_REGISTRY-}externalthecarrier
    build:
      context: .
      dockerfile: src/External.TheCarrier/Dockerfile
    ports:
      - 50082:80

  expertstore.shipment:
    image: ${DOCKER_REGISTRY-}expertstoreshipment
    build:
      context: .
      dockerfile: src/ExpertStore.Shipment/Dockerfile
    ports:
      - 50081:80

